name: quizbowl-build-deploy
run-name: ${{ github.actor }} running build/deploy
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        concurrency: production
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v3
            - name: 'Node Setup'
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: 'Npm Dependency Installs'
              run: npm ci
            - name: 'Build Script'
              run: npm run build --if-present
            - name: 'Run Tests'
              run: npm run test --if-present
            - name: 'Post build status Slack'
              id: slack
              uses: slackapi/slack-github-action@v1.24.0
              with:
                # Slack channel id, channel name, or user id to post message.
                # See also: https://api.slack.com/methods/chat.postMessage#channels
                # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
                channel-id: 'C05SM84462J'
                # For posting a simple plain text message
                slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            - name: 'Setup Pages'
              uses: actions/configure-pages@v3
            - name: Fix permissions
              run: |
                    chmod -c -R +rX "_site/" | while read line; do
                    echo "::warning title=Invalid file permissions automatically fixed::$line"
                    done
            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v2
            - name: 'Post artifact status Slack'
              id: slack-artifact
              uses: slackapi/slack-github-action@v1.24.0
              with:
                # Slack channel id, channel name, or user id to post message.
                # See also: https://api.slack.com/methods/chat.postMessage#channels
                # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
                channel-id: 'C05SM84462J'
                # For posting a simple plain text message
                slack-message: "GitHub artifact upload result: ${{ job.status }}\n"

    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build

      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      permissions:
       pages: write      # to deploy to Pages
       id-token: write   # to verify the deployment originates from an appropriate source


      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
        - name: 'Post deploy status Slack'
          id: slack-deploy
          uses: slackapi/slack-github-action@v1.24.0
          with:
            # Slack channel id, channel name, or user id to post message.
            # See also: https://api.slack.com/methods/chat.postMessage#channels
            # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
            channel-id: 'C05SM84462J'
            # For posting a simple plain text message
            slack-message: "GitHub deploy result: ${{ job.status }}\n"